#############################################################
#
# SwiftLintコードの品質チェックツールの設定ファイル
#
# <参照>
# ・SwiftLintのRules全まとめ
# https://qiita.com/kagemiku/items/80e6d905dc0059c342b3
#
#############################################################

#---------------------------------------------
# 無効にするルール
#---------------------------------------------
disabled_rules:
  # 各行の末尾に空白類文字を書くべきでない．
  - trailing_whitespace

  # try!の使用は避けるべき
  # - force_try

  # 強制キャスト(as!)は避けるべき．
  - force_cast

  # 1行における文字数は多くなりすぎないように．
  - line_length

  # 関数の引数は少なく(デフォルトだと6個で警告が出ます)
  - function_parameter_count

  # 最後の引数のクロージャをTrailing Closureとして渡すことを警告する
  - multiple_closures_with_trailing_closure



#---------------------------------------------
# デフォルト無効で有効にするルール
#---------------------------------------------
opt_in_rules:
  #条件文は始まった行の次の行でreturnするべき．
  - conditional_returns_on_newline

  # 要素が何もないことを確認する際はcount == 0よりもisEmptyを用いてチェックする
  - empty_count

  # publicな宣言はドキュメント化されているべき
  - missing_docs

  # 演算子を使用する際は前後に1つのスペースを開けるべき
  - operator_usage_whitespace

#---------------------------------------------
# 対象のファイル・フォルダ
# デフォルトからフォルダ名を変更していない場合、プロジェクト名と同名のフォルダを指定すればいい
#---------------------------------------------
included:
#  - {プロジェクト名}

#---------------------------------------------
# 対象外のファイル・フォルダ
# CocoaPodsでインストールしたライブラリは対象外とする
#---------------------------------------------
excluded:
  - Pods

#---------------------------------------------
# 個別の詳細設定
#---------------------------------------------
# 1つのファイルの行数制限
file_length:
  warning: 1000
  error: 1200

# １つの関数の行数
function_body_length:
  warning: 150
  error: 200

# Class, Struct, Enumの行数
type_body_length:
  warning: 400
  error: 500

# 循環的複雑度の違反
cyclomatic_complexity:
  warning: 100
  error: 120